#!/usr/bin/env python3
"""Render Hugo paper bundles from manual and Scholar publication data."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse

try:
    import yaml
except ImportError as exc:  # pragma: no cover - only used for a clearer setup error
    raise SystemExit(
        "PyYAML is required. Install it with: "
        "python -m pip install -r scripts/requirements.txt"
    ) from exc

from publication_data import load_merged_publications


ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "data" / "publications.yml"
SCHOLAR_DATA_FILE = ROOT / "data" / "publications.scholar.yml"
PROJECT_DATA_FILE = ROOT / "data" / "paper_projects.yml"
PAPERS_DIR = ROOT / "content" / "papers"
GENERATED_NOTICE = (
    "<!-- Generated by scripts/render_papers.py from publication data. "
    "Do not edit this file directly. -->"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with an error when generated pages are out of date.",
    )
    return parser.parse_args()


def load_publications() -> list[dict[str, Any]]:
    return load_merged_publications(DATA_FILE, SCHOLAR_DATA_FILE)


def load_project_pages(path: Path = PROJECT_DATA_FILE) -> dict[str, dict[str, Any]]:
    if not path.exists():
        return {}
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(payload, dict) or not isinstance(payload.get("projects"), dict):
        raise ValueError("Project data must contain a projects mapping")
    projects = payload["projects"]
    for slug, project in projects.items():
        validate_slug(slug)
        if not isinstance(project, dict):
            raise ValueError(f"{slug}: project must be a mapping")
        require_fields(project, ("venue", "summary", "citation_key"), slug)
        if "citation" in project:
            validate_official_citation(project["citation"], project["citation_key"], slug)
        for link in project.get("links") or []:
            if not isinstance(link, dict) or not link.get("label"):
                raise ValueError(f"{slug}: every project link needs a label")
            if bool(link.get("url")) == bool(link.get("file")):
                raise ValueError(f"{slug}: each project link needs exactly one URL or file")
            if link.get("url") and urlparse(str(link["url"])).scheme not in {"http", "https"}:
                raise ValueError(f"{slug}: project links must use HTTP or HTTPS")
        figures = [project.get("teaser"), project.get("poster")]
        for section in project.get("sections") or []:
            require_fields(section, ("title", "text"), slug)
            figures.append(section.get("figure"))
        for figure in filter(None, figures):
            require_fields(figure, ("image", "alt"), slug)
        for highlight in project.get("highlights") or []:
            require_fields(highlight, ("title", "text"), slug)
    return projects


def validate_official_citation(citation: Any, citation_key: str, slug: str) -> None:
    """Validate a stored official export without reconstructing its fields."""
    if not isinstance(citation, dict):
        raise ValueError(f"{slug}: citation must be a mapping")
    require_fields(citation, ("source_name", "source_url", "bibtex"), slug)
    source = urlparse(str(citation["source_url"]))
    if source.scheme not in {"http", "https"} or not source.netloc:
        raise ValueError(f"{slug}: citation source must be an HTTP or HTTPS URL")
    bibtex = citation["bibtex"]
    if not isinstance(bibtex, str):
        raise ValueError(f"{slug}: citation BibTeX must be text")
    header = re.match(r"\s*@inproceedings\s*\{\s*([^,]+),", bibtex, re.IGNORECASE)
    if not header or header.group(1).strip() != citation_key or not bibtex.rstrip().endswith("}"):
        raise ValueError(f"{slug}: citation must be a complete BibTeX entry with its official key")
    for field in ("title", "author", "booktitle", "year"):
        if not re.search(rf"^\s*{field}\s*=\s*\{{", bibtex, re.MULTILINE | re.IGNORECASE):
            raise ValueError(f"{slug}: citation is missing {field}")


def validate_slug(value: Any) -> str:
    slug = str(value or "").strip()
    if not slug or slug in {".", ".."} or "/" in slug or "\\" in slug:
        raise ValueError(f"Invalid publication slug: {value!r}")
    return slug


def require_fields(publication: dict[str, Any], fields: Iterable[str], slug: str) -> None:
    missing = [field for field in fields if publication.get(field) in (None, "", [])]
    if missing:
        raise ValueError(f"{slug}: missing required fields: {', '.join(missing)}")


def build_front_matter(
    publication: dict[str, Any], project: dict[str, Any] | None = None
) -> dict[str, Any]:
    front_matter: dict[str, Any] = {
        "title": publication["title"],
        "date": str(publication["date"]),
        "tags": publication["tags"],
        "author": publication["authors"],
        "description": publication["description"],
        "venue": publication.get("venue") or "",
    }

    if publication.get("summary"):
        front_matter["summary"] = publication["summary"]

    if publication.get("cover"):
        cover = dict(publication["cover"])
        cover.setdefault("relative", True)
        front_matter["cover"] = cover

    if publication.get("edit_post"):
        edit_post = publication["edit_post"]
        rendered_edit_post: dict[str, Any] = {}
        if edit_post.get("url"):
            rendered_edit_post["URL"] = edit_post["url"]
        if edit_post.get("text"):
            rendered_edit_post["Text"] = edit_post["text"]
        if rendered_edit_post:
            front_matter["editPost"] = rendered_edit_post

    extra_front_matter = publication.get("extra_front_matter") or {}
    if not isinstance(extra_front_matter, dict):
        raise ValueError("extra_front_matter must be a mapping")
    front_matter.update(extra_front_matter)
    if project:
        abstract = project.get("abstract") or publication.get("abstract")
        if not abstract:
            raise ValueError(f"{publication['slug']}: project page needs an abstract")
        front_matter.update({
            "title": project.get("title") or publication["title"],
            "layout": "project",
            "project": publication["slug"],
            "abstract": abstract,
            "description": project["summary"],
            "conference": publication.get("venue") or project["venue"],
            "ShowCodeCopyButtons": False,
        })
        if not front_matter.get("hidePublicationLinks"):
            for link in project.get("links") or []:
                if link["label"] == "Paper":
                    front_matter["pdf"] = link.get("url") or (
                        f"https://maojiangsu.github.io/papers/{publication['slug']}/{link['file']}"
                    )
                    break
    return front_matter


def build_body(publication: dict[str, Any]) -> str:
    sections = [GENERATED_NOTICE]

    downloads = publication.get("downloads") or []
    if downloads:
        lines = ["##### Download", ""]
        for download in downloads:
            target = download.get("file") or download.get("url")
            if not download.get("label") or not target:
                raise ValueError("Each download needs label and file/url fields")
            lines.append(f"- [{download['label']}]({target})")
        sections.append("\n".join(lines))

    abstract = str(publication.get("abstract") or "").strip()
    if abstract:
        sections.append(f"##### Abstract\n\n{abstract}")

    figure = publication.get("figure") or {}
    if figure:
        if not figure.get("image"):
            raise ValueError("figure.image is required when a figure is configured")
        title = figure.get("title") or "Figure"
        sections.append(f"##### {title}\n\n![]({figure['image']})")

    return "\n\n---\n\n".join(sections)


def render_publication(
    publication: dict[str, Any], project: dict[str, Any] | None = None
) -> str:
    front_matter = yaml.safe_dump(
        build_front_matter(publication, project),
        allow_unicode=True,
        sort_keys=False,
        width=1000,
    ).rstrip()
    body = GENERATED_NOTICE if project else build_body(publication)
    return f"---\n{front_matter}\n---\n\n{body}\n"


def is_external_reference(value: str) -> bool:
    return bool(urlparse(value).scheme) or value.startswith("//")


def local_asset_references(
    publication: dict[str, Any], project: dict[str, Any] | None = None
) -> set[str]:
    references: set[str] = set()
    for container, key in (
        (publication.get("cover") or {}, "image"),
        (publication.get("figure") or {}, "image"),
    ):
        value = container.get(key)
        if value and not is_external_reference(str(value)):
            references.add(str(value))

    for download in publication.get("downloads") or []:
        value = download.get("file")
        if value and not is_external_reference(str(value)):
            references.add(str(value))
    if project:
        figures = [project.get("teaser"), project.get("poster")]
        figures.extend(section.get("figure") for section in project.get("sections") or [])
        for figure in filter(None, figures):
            references.add(str(figure["image"]))
        for link in project.get("links") or []:
            if link.get("file"):
                references.add(str(link["file"]))
    return references


def validate_local_assets(
    publication: dict[str, Any], paper_dir: Path, slug: str,
    project: dict[str, Any] | None = None,
) -> None:
    base = paper_dir.resolve()
    for reference in sorted(local_asset_references(publication, project)):
        asset = (paper_dir / reference).resolve()
        try:
            asset.relative_to(base)
        except ValueError as exc:
            raise ValueError(f"{slug}: asset leaves the paper directory: {reference}") from exc
        if not asset.is_file():
            raise ValueError(f"{slug}: referenced asset does not exist: {reference}")


def main() -> int:
    args = parse_args()
    publications = load_publications()
    projects = load_project_pages()
    unknown_projects = set(projects) - {p.get("slug") for p in publications}
    if unknown_projects:
        raise ValueError(f"Project pages reference unknown publications: {sorted(unknown_projects)}")
    seen_slugs: set[str] = set()
    stale_pages: list[Path] = []

    for publication in publications:
        if not isinstance(publication, dict):
            raise ValueError("Each publication entry must be a mapping")

        slug = validate_slug(publication.get("slug"))
        if slug in seen_slugs:
            raise ValueError(f"Duplicate publication slug: {slug}")
        seen_slugs.add(slug)
        require_fields(
            publication,
            ("title", "date", "tags", "authors", "description"),
            slug,
        )

        paper_dir = PAPERS_DIR / slug
        project = projects.get(slug)
        validate_local_assets(publication, paper_dir, slug, project)
        output_file = paper_dir / "index.md"
        rendered = render_publication(publication, project)
        current = output_file.read_text(encoding="utf-8") if output_file.exists() else None

        if current == rendered:
            continue
        if args.check:
            stale_pages.append(output_file.relative_to(ROOT))
            continue

        paper_dir.mkdir(parents=True, exist_ok=True)
        output_file.write_text(rendered, encoding="utf-8", newline="\n")

    if stale_pages:
        print("Generated publication pages are out of date:", file=sys.stderr)
        for page in stale_pages:
            print(f"  - {page}", file=sys.stderr)
        print("Run: python scripts/render_papers.py", file=sys.stderr)
        return 1

    action = "Checked" if args.check else "Rendered"
    print(f"{action} {len(publications)} merged publication pages")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, TypeError, ValueError, yaml.YAMLError) as exc:
        print(f"Publication generation failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
