#!/usr/bin/env python3
"""Render Hugo paper bundles from manual and Scholar publication data."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse

try:
    import yaml
except ImportError as exc:  # pragma: no cover - only used for a clearer setup error
    raise SystemExit(
        "PyYAML is required. Install it with: "
        "python -m pip install -r scripts/requirements.txt"
    ) from exc

from publication_data import load_merged_publications


ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "data" / "publications.yml"
SCHOLAR_DATA_FILE = ROOT / "data" / "publications.scholar.yml"
PAPERS_DIR = ROOT / "content" / "papers"
GENERATED_NOTICE = (
    "<!-- Generated by scripts/render_papers.py from publication data. "
    "Do not edit this file directly. -->"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with an error when generated pages are out of date.",
    )
    return parser.parse_args()


def load_publications() -> list[dict[str, Any]]:
    return load_merged_publications(DATA_FILE, SCHOLAR_DATA_FILE)


def validate_slug(value: Any) -> str:
    slug = str(value or "").strip()
    if not slug or slug in {".", ".."} or "/" in slug or "\\" in slug:
        raise ValueError(f"Invalid publication slug: {value!r}")
    return slug


def require_fields(publication: dict[str, Any], fields: Iterable[str], slug: str) -> None:
    missing = [field for field in fields if publication.get(field) in (None, "", [])]
    if missing:
        raise ValueError(f"{slug}: missing required fields: {', '.join(missing)}")


def build_front_matter(publication: dict[str, Any]) -> dict[str, Any]:
    front_matter: dict[str, Any] = {
        "title": publication["title"],
        "date": str(publication["date"]),
        "tags": publication["tags"],
        "author": publication["authors"],
        "description": publication["description"],
        "venue": publication.get("venue") or "",
    }

    if publication.get("summary"):
        front_matter["summary"] = publication["summary"]

    if publication.get("cover"):
        cover = dict(publication["cover"])
        cover.setdefault("relative", True)
        front_matter["cover"] = cover

    if publication.get("edit_post"):
        edit_post = publication["edit_post"]
        rendered_edit_post: dict[str, Any] = {}
        if edit_post.get("url"):
            rendered_edit_post["URL"] = edit_post["url"]
        if edit_post.get("text"):
            rendered_edit_post["Text"] = edit_post["text"]
        if rendered_edit_post:
            front_matter["editPost"] = rendered_edit_post

    extra_front_matter = publication.get("extra_front_matter") or {}
    if not isinstance(extra_front_matter, dict):
        raise ValueError("extra_front_matter must be a mapping")
    front_matter.update(extra_front_matter)
    return front_matter


def build_body(publication: dict[str, Any]) -> str:
    sections = [GENERATED_NOTICE]

    downloads = publication.get("downloads") or []
    if downloads:
        lines = ["##### Download", ""]
        for download in downloads:
            target = download.get("file") or download.get("url")
            if not download.get("label") or not target:
                raise ValueError("Each download needs label and file/url fields")
            lines.append(f"- [{download['label']}]({target})")
        sections.append("\n".join(lines))

    abstract = str(publication.get("abstract") or "").strip()
    if abstract:
        sections.append(f"##### Abstract\n\n{abstract}")

    figure = publication.get("figure") or {}
    if figure:
        if not figure.get("image"):
            raise ValueError("figure.image is required when a figure is configured")
        title = figure.get("title") or "Figure"
        sections.append(f"##### {title}\n\n![]({figure['image']})")

    return "\n\n---\n\n".join(sections)


def render_publication(publication: dict[str, Any]) -> str:
    front_matter = yaml.safe_dump(
        build_front_matter(publication),
        allow_unicode=True,
        sort_keys=False,
        width=1000,
    ).rstrip()
    return f"---\n{front_matter}\n---\n\n{build_body(publication)}\n"


def is_external_reference(value: str) -> bool:
    return bool(urlparse(value).scheme) or value.startswith("//")


def local_asset_references(publication: dict[str, Any]) -> set[str]:
    references: set[str] = set()
    for container, key in (
        (publication.get("cover") or {}, "image"),
        (publication.get("figure") or {}, "image"),
    ):
        value = container.get(key)
        if value and not is_external_reference(str(value)):
            references.add(str(value))

    for download in publication.get("downloads") or []:
        value = download.get("file")
        if value and not is_external_reference(str(value)):
            references.add(str(value))
    return references


def validate_local_assets(publication: dict[str, Any], paper_dir: Path, slug: str) -> None:
    base = paper_dir.resolve()
    for reference in sorted(local_asset_references(publication)):
        asset = (paper_dir / reference).resolve()
        try:
            asset.relative_to(base)
        except ValueError as exc:
            raise ValueError(f"{slug}: asset leaves the paper directory: {reference}") from exc
        if not asset.is_file():
            raise ValueError(f"{slug}: referenced asset does not exist: {reference}")


def main() -> int:
    args = parse_args()
    publications = load_publications()
    seen_slugs: set[str] = set()
    stale_pages: list[Path] = []

    for publication in publications:
        if not isinstance(publication, dict):
            raise ValueError("Each publication entry must be a mapping")

        slug = validate_slug(publication.get("slug"))
        if slug in seen_slugs:
            raise ValueError(f"Duplicate publication slug: {slug}")
        seen_slugs.add(slug)
        require_fields(
            publication,
            ("title", "date", "tags", "authors", "description"),
            slug,
        )

        paper_dir = PAPERS_DIR / slug
        validate_local_assets(publication, paper_dir, slug)
        output_file = paper_dir / "index.md"
        rendered = render_publication(publication)
        current = output_file.read_text(encoding="utf-8") if output_file.exists() else None

        if current == rendered:
            continue
        if args.check:
            stale_pages.append(output_file.relative_to(ROOT))
            continue

        paper_dir.mkdir(parents=True, exist_ok=True)
        output_file.write_text(rendered, encoding="utf-8", newline="\n")

    if stale_pages:
        print("Generated publication pages are out of date:", file=sys.stderr)
        for page in stale_pages:
            print(f"  - {page}", file=sys.stderr)
        print("Run: python scripts/render_papers.py", file=sys.stderr)
        return 1

    action = "Checked" if args.check else "Rendered"
    print(f"{action} {len(publications)} merged publication pages")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, TypeError, ValueError, yaml.YAMLError) as exc:
        print(f"Publication generation failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
